### ISSUE TITLE
Add support for format JSON-API 1.1

### ISSUE THREAD

**Issue by Art4** [Art4/json-api-client#78]
[JSON:API v1.1](https://jsonapi.org/format/1.1/) was finalized September 30, 2022!

### TODO

- [ ] New `lid` property in Resource Objects https://jsonapi.org/format/1.1/#document-resource-objects
- [ ] New `lid` property in Resource Identifier Objects https://jsonapi.org/format/1.1/#document-resource-identifier-objects
- [ ] New `ext` and `profile` properties in Jsonapi object https://jsonapi.org/format/1.1/#document-jsonapi-object
- [ ] New `describedby` property in the top level Links object https://jsonapi.org/format/1.1/#document-top-level
- [ ] New possible members in top level Object defined by an extension https://jsonapi.org/format/1.1/#document-top-level
- [ ] New possible member in Relationship Objects defined by an extension https://jsonapi.org/format/1.1/#document-resource-object-relationships
- [ ] New possible member in Relationship Link Objects defined by an extension https://jsonapi.org/format/1.1/#document-resource-object-relationships
- [ ] Links can contain a string (instead of an object) https://jsonapi.org/format/1.1/#document-links
- [ ] Link Objects can contain new members like `rel`, `title`, `describedby`, `type` and `hreflang` https://jsonapi.org/format/1.1/#auto-id--link-objects
- [ ] New @-Members https://jsonapi.org/format/1.1/#document-member-names-at-members
- [ ] New `header` member in Error Source objects https://jsonapi.org/format/1.1/#error-objects
